autor = input("Podaj nazwisko autora: ")
tytul = input ("Podaj tytul ksiazki: ")
liczba_str = input("Podaj liczbe stron: ")
liczba_str.isnumeric()
autor.isalpha()
tytul.isalpha()
autor = autor.capitalize()
tytul = tytul.capitalize()
book = autor + " " + tytul + " liczba stron " + liczba_str
print(book)
len(book)